on:
  push:
    branches: main
  
  schedule:
    # Every week
    - cron: "0 0 1 * *" 

name: Sync

jobs:
  render:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # - name: git-sync
      #  uses: wei/git-sync@v3
      #  with:
      #    source_repo: "source_org/repository"
      #    source_branch: "main"
      #    destination_repo: "destination_org/repository"
      #    destination_branch: "main"

